// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC76YirHnOEhtkUIoNHVieN_1muU5eKQt4',
    appId: '1:325502280885:web:c2bb80803b31e39038cafc',
    messagingSenderId: '325502280885',
    projectId: 'enigma-sales',
    authDomain: 'enigma-sales.firebaseapp.com',
    storageBucket: 'enigma-sales.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE7Buc0JuQtIHpkIGK-MJC6g_x5iyRBpg',
    appId: '1:325502280885:ios:8b03e365df615c6638cafc',
    messagingSenderId: '325502280885',
    projectId: 'enigma-sales',
    storageBucket: 'enigma-sales.appspot.com',
    iosClientId: '325502280885-t8lt1puviguo5vgks04ucinqgjck0lvj.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
